language: python
python:
  - 3.5
  - 3.6
cache: pip
install:
  - pip install -r requirements.txt
  - pip install coverage coveralls
  - python setup.py install
script:
  # Actual tests.
  - coverage run --source=rloopDefinitionApp setup.py test
  # This shouldn't be failing so, why not!
  - python rloopDefinitionApp
after_success:
  - coveralls
